### ISSUE TITLE
`s` should select input, just focus

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/purescript-docs-search#11]
e.g. $('input').select() is the behavior you want when you want the input to be focused with all of the text selected, so you can readily replace the contents

**Comment by justinwoo** [comment]
https://github.com/spacchetti/purescript-docs-search/blob/ba841411e9ff95f812db0f7163cc3079b473c09f/src/Docs/Search/App/SearchField.purs#L69

Web.focus -> Web.select might do it just enough

**Comment by klntsky** [comment]
Sure. #12
