### ISSUE TITLE
Include built-in definitions

### ISSUE THREAD

**Issue by klntsky** [spacchetti/purescript-docs-search#31]
From spacchetti/spago#534.

**Comment by klntsky** [comment]
It is possible to resolve this by creating a Haskell binary that gets the jsons from `Language.PureScript.Docs`. These jsons can then be included into the bundle.

The problem is that the app is not strictly tied to PS versions, so these built-in docs may be wrong.

**Comment by f-f** [comment]
@klntsky yeah having a separate binary is not going to work as we'll need to work with different versions of the compiler. I think we should open an issue in the compiler and have it output the JSONs for the Prim modules when building docs, it should not be too much work
