### ISSUE TITLE
Add `install` npm script

### ISSUE THREAD

**Issue by m-bock** [spacchetti/purescript-docs-search#35]
When trying out the new side bar feature, I realized that the `build` script is not triggered on running `npm install`.

I guess if there was an `install` script it would build to `dist` and then register the CLI binary in `node_modules/.bin` so that the following would work:

```
npm install purescript-docs-search
npm run purescript-docs-search
```

**Comment by klntsky** [comment]
Thank you for this report.

We are only using NPM to distribute the precompiled binary. Compiling PureScript in a preinstall script would be too inconvenient for most users.

`npm install purescript-docs-search` does register the binary in `node_modules/.bin`.

However, `npm run purescript-docs-search` [is a shortand](https://docs.npmjs.com/cli-commands/run-script.html) for `npm run-script purescript-docs-search`, which is supposed to run `scripts["purescript-docs-search"]` from the currently present `package.json` - I am pretty sure this is not what you are trying to accomplish.

Perhaps you might want to use [npx](https://github.com/npm/npx): `npm i -g npx && npx purescript-docs-search`.

**Comment by klntsky** [comment]
I added "development" section to the README in #36.

**Comment by f-f** [comment]
I believe we can close this, right?
