### ISSUE TITLE
Improvements to module grouping

### ISSUE THREAD

**Issue by f-f** [spacchetti/purescript-docs-search#39]
The latest version (`0.0.9`) includes the optional grouping for modules in the sidebar and the index proposed in #20, which is very lovely. While using it I noticed that it could do with some small UX improvements to make it more intuitive:
- module grouping should be on by default, since it's really the better way to look at things
- the project modules don't seem to be included in a package when grouping. I propose that we include them (we can get the project name from the Spago config), and we always list the project package at the top of the list of packages
- clicking on the package name opens up a subtree in the list, but the icon on the left of the name is still a `-`, which doesn't communicate that it's an expandable item. Some kind of arrow, like `▸`, would probably be clearer
- the title (in both the sidebar and the index) is still "Modules", even when grouping by packages

Thoughts?

**Comment by klntsky** [comment]
These are good points, thank you!

> I propose that we include them (we can get the project name from the Spago config)

I believe the best way to achieve this is to pass package name as a command line argument (we don't have access to `spago.dhall` from PS).

> Some kind of arrow, like ▸, would probably be clearer

I wanted to preserve the original look of Pursuit as much as I can, cause the UI is really well-thought, so I decided to change arrows (like on the screenshot in #34) back to dashes. My motivation was that if the user clicked the "group by packages" checkbox, they are likely to expect the package names to become expandable.

**Comment by klntsky** [comment]
Additionally, it might be a good idea to show links to package repos under their names. We already have this info from `bower.json`s. However, since PS package format is likely to change in the near future due to problems with bower, I'm not sure if it is worth the effort.

**Comment by f-f** [comment]
> Additionally, it might be a good idea to show links to package repos under their names. We already have this info from bower.jsons. However, since PS package format is likely to change in the near future due to problems with bower, I'm not sure if it is worth the effort.

Agreed, I'd wait on this

> I wanted to preserve the original look of Pursuit as much as I can, cause the UI is really well-thought, so I decided to change arrows (like on the screenshot in #34) back to dashes. My motivation was that if the user clicked the "group by packages" checkbox, they are likely to expect the package names to become expandable.

I was not expecting that, so I got confused. I think the screenshot in #34 is much more intuitive, and good UI in line with the rest of Pursuit :slightly_smiling_face:

**Comment by f-f** [comment]
Fixed in #42
