### ISSUE TITLE
API for integration with editors (hoogle-like)

### ISSUE THREAD

**Issue by mkohlhaas** [spacchetti/purescript-docs-search#56]
Could the command line return JSON/XML/Dhall or some other data output?

Would be great e.g. for third-party integration.

**Comment by klntsky** [comment]
@mkohlhaas 
Dhall is certainly not for machines. JSON - I think that's possible, but could you please provide some example use cases?

**Comment by mkohlhaas** [comment]
Hi Vladimir,

e.g. you could use it in your editor. There are similar plugins for Hoogle, e.g. [fzf-hoogle.vim](https://github.com/monkoose/fzf-hoogle.vim) and many others.

See also the [Hoogle JSON API](https://github.com/ndmitchell/hoogle/blob/master/docs/API.md#json-api).

**Comment by klntsky** [comment]
@mkohlhaas this is achievable.

I'm going to post it to discord to see if the feature gets enough interest.

**Comment by klntsky** [comment]
There was not enough interest, but I think the issue should remain open as someone may prioritize it and actually start working on this feature.
