### ISSUE TITLE
Merge klntsky/fixes-for-rare-types into master?

### ISSUE THREAD

**Issue by ursi** [spacchetti/purescript-docs-search#60]
Is this branch good to merge into master? I have a project where `build-index` has errors without it.

**Comment by klntsky** [comment]
Hi, we need to update the Halogen app before I can merge. Unfortunately, I'm low on time...

**Comment by ursi** [comment]
Why exactly does it need to be updated? When I merge it and run it it seems to work fine.

**Comment by klntsky** [comment]
Done
