### ISSUE TITLE
Merging in the Spago repo

### ISSUE THREAD

**Issue by f-f** [spacchetti/purescript-docs-search#68]
I would like to merge this repository into the Spago repo - now that everything is PureScript over there I think we can (or at least I can) offer better maintenance if the code is sitting over there.

Thoughts @klntsky?

**Comment by klntsky** [comment]
There is some value in providing it separately. For example we use it in CI at MLabs, with CLI arguments that make behavior more fine-grained (spago alone does not allow that).

Wouldn't making it a PS lib dependency instead of a binary dependency cover both usecases?

**Comment by f-f** [comment]
It would become a PS lib dependency in any case - that is, not fully part of the Spago codebase, just another package sitting there.

We could integrate the CLI part in Spago CLI, so we would have less CLIs to maintain 😄

**Comment by f-f** [comment]
Another approach could be to just fork the codebase in Spago (as it happened for PSA, where the preference was to not touch the existing codebase) so we can move quickly, but I'd like to avoid that if possible.

**Comment by f-f** [comment]
@klntsky I went ahead and [merged this repo (preserving the full history) into Spago](https://github.com/purescript/spago/commit/dda0f96e61a36394f74d3173188eba12e4d9ffe7), so we can prototype quickly over there without having to deal with CI, preserving compatibility, and so on.

We have a few options for how to deal with divergence:
1. we port the features that we need over into Spago, and archive this repo
2. or we keep this codebase alive and mostly still, with optional backporting of some changes
