### ISSUE TITLE
Listing all results from doc-search in xml format

### ISSUE THREAD

**Issue by mikesol** [spacchetti/purescript-docs-search#72]
Great work on this package!

I'm experimenting with a different indexing method using [SBERT](https://sbert.net/) and [FAISS](https://github.com/facebookresearch/faiss).

I'm wondering if it's possible to dump the entire index in xml form. For example:

```xml
<entry>
  <package>purescript-lists</package>
  <module>Data.List</module>
  <id>singleton</id>
  <def>singleton :: forall a. a -> List a</def>
  <doc>Create a list with a single element.

Running time: `O(1)`</doc>
</entry>
```

It's easier to work with SBERT when things are organized like this.

If you have pointers on how to hack at the repo to get there, I can give it a shot!

**Comment by f-f** [comment]
This project has been merged into spago, [here](https://github.com/purescript/spago/tree/master/docs-search) - this repo is missing the last two years worth of patches/updates.

**Comment by mikesol** [comment]
Thanks, will ask there!
